# Generated by Django 6.0.2 on 2026-03-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('recieve_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('recieved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_to_csv', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.category')),
            ],
        ),
    ]
