# Generated by Django 6.0.2 on 2026-04-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='recieve_quantity',
            new_name='receive_quantity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='recieved_by',
            new_name='received_by',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='issue_quantity',
            new_name='issued_quantity',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='recieve_quantity',
            new_name='receive_quantity',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='recieved_by',
            new_name='received_by',
        ),
    ]
