# Generated by Django 6.0.2 on 2026-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_rename_recieve_quantity_stock_receive_quantity_and_more'),
    ]

    operations = [
    ]
