# Generated by Django 6.0.2 on 2026-03-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='export_to_csv',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='reorder_level',
        ),
    ]
