# Generated by Django 6.0.2 on 2026-03-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_remove_stockhistory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockhistory',
            table='StockHistory',
        ),
    ]
