# Generated by Django 6.0.2 on 2026-03-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_stock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
    ]
