# Generated by Django 6.0.2 on 2026-04-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20260403_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='issue_quantity',
            new_name='issued_quantity',
        ),
    ]
