# Generated by Django 6.0.2 on 2026-04-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_rename_issue_quantity_stock_issued_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='receive_quantity',
            new_name='received_quantity',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='receive_quantity',
            new_name='received_quantity',
        ),
    ]
