# Generated by Django 6.0.2 on 2026-03-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
