# Generated by Django 6.0.2 on 2026-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_alter_stock_last_updated_alter_stock_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issue_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
